server:
  name: go-sql-layer-architecture-sample
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://xkjofgbu:MKmT3B0PPIZ6pr057wEHFUMvtad5nXex@satao.db.elephantsql.com/xkjofgbu

log:
  level: info
  fields: appId,service,mobileNo,creditCard,corrId
  caller_level: "debug,error,panic"
  caller_skip: 3
  map:
    time: "@timestamp"
    msg: message
    caller: caller
    function: func
    stacktrace: stacktrace
middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
  masks: mobileNo
  constants:
    app_id: "123"
    service: log-sample
  map:
    mobile_no: header.mobileNo
    credit_Card: header.creditCard
    corr_id: header.corrId
    email: body.email
    username: body.username


client:
  endpoint:
    url: "http://localhost:8080/users"
    timeout: 1s
  log:
    log: true
    size: size
    status: status
    request: request
    response: response
